# Generated by Django 5.2.8 on 2025-11-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField(blank=True, help_text='Link ke website live (opsional)', null=True)),
                ('date_completed', models.DateField()),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
    ]
